# Generated by Django 4.0.5 on 2022-06-29 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afterline', '0002_alter_afterlineuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterlineuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
