# Generated by Django 4.0.5 on 2022-07-02 04:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterline', '0003_alter_afterlineuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineuser')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineuser')),
            ],
        ),
    ]
