# Generated by Django 4.0.5 on 2022-07-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterline', '0004_campaign_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
