# Generated by Django 4.0.5 on 2022-07-04 03:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('afterline', '0005_alter_campaign_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterlineOwnedResource',
            fields=[
                ('resource_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.TextField(choices=[('Unsorted', [])])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineuser')),
            ],
        ),
        migrations.CreateModel(
            name='AfterlinePermission',
            fields=[
                ('perm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.permission')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineuser')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'game')},
        ),
        migrations.CreateModel(
            name='ResourceOwnershipTransferNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('viewed', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResourceOwnershipTransferNotification_receiver', to='afterline.afterlineuser')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineownedresource')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResourceOwnershipTransferNotification_sender', to='afterline.afterlineuser')),
            ],
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField()),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('viewed', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageNotification_receiver', to='afterline.afterlineuser')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MessageNotification_sender', to='afterline.afterlineuser')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('viewed', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.campaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineuser')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('viewed', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.campaign')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineuser')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('edit_perm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit', to='afterline.afterlinepermission')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineownedresource')),
                ('view_perm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view', to='afterline.afterlinepermission')),
            ],
        ),
    ]
