# Generated by Django 4.0.5 on 2022-07-04 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterline', '0006_afterlineownedresource_afterlinepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineownedresource'),
        ),
        migrations.AlterField(
            model_name='afterlineownedresource',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineuser'),
        ),
        migrations.AlterField(
            model_name='afterlineownedresource',
            name='resource_type',
            field=models.TextField(choices=[('Unsorted', (('calendar', 'Calendar'), ('campaign', 'Campaign')))]),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='edit_perm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Calendar_edit', to='afterline.afterlinepermission'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afterline.afterlineownedresource'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='view_perm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Calendar_view', to='afterline.afterlinepermission'),
        ),
    ]
